# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            mrsideshowjack
tagline:          'personal site'
description:      'personal site'
url:              http://sideshowjack.uk/blog
baseurl:          '/blog'
production_url :  http://mrsideshowjack.github.io.com/blog
BASE_PATH :       http://sideshowjack.uk/blog

author:
  name:           'Jack Mason'
  url:            https://twitter.com/mrsideshowjack

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mrsideshowjack/mrsideshowjack.github.io
