# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            mrsideshowjack
tagline:          'personal site'
description:      'personal site'
url:              http://sideshowjack.uk
baseurl:          /blog

author:
  name:           'JAck Mason'
  url:            https://twitter.com/mrsideshowjack

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mrsideshowjack/mrsideshowjack.github.io
